---
title: "DEA_nkamat"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
input <- matrix(c(150, 400, 320, 520, 350, 320, 0.2, 0.7, 1.2, 2, 1.2, 0.7), ncol = 2)
output <- matrix(c(14000, 14000, 42000, 28000, 19000, 14000, 3500, 21000, 10500, 42000, 25000, 15000), ncol = 2)
input
output
```


```{r}
colnames(input) <- c('staff_hours/day', 'supplies/day')
colnames(output) <- c('reimbursed_pdays', 'privately_pdays')
input
output
```
```{r}
library(lpSolveAPI)
library(ucminf)
library(Benchmarking)
```

```{r}
f <- dea(input,output, RTS ='FDH')
f
```
```{r}
peers(f)
lambda(f)
```
```{r}
dea.plot.frontier(input, output, RTS = 'fdh', xlab = 'input', ylab = 'output', main = 'Input vs Output using FDH')
```

```{r}
c <- dea(input,output, RTS ='CRS')
c
```

```{r}
peers(c)
lambda(c)
```

```{r}
dea.plot.frontier(input, output, RTS = 'crs', xlab = 'input', ylab = 'output', main = 'Input vs Output using CRS')
```

```{r}
d <- dea(input, output, RTS = 'drs')
d
```


```{r}
peers(d)
lambda(d)
```
```{r}
dea.plot.frontier(input, output, RTS = 'drs', xlab = 'input', ylab = 'output', main = 'Input vs Output using DRS')

```

```{r}
i <- dea(input, output, RTS = 'irs')
i
```


```{r}
peers(i)
lambda(i)
```

```{r}
dea.plot.frontier(input, output, RTS = 'irs', xlab = 'input', ylab = 'output', main = 'Input vs Output using IRS')
```


```{r}
v <- dea(input, output, RTS = 'vrs')
v

```

```{r}
peers(v)
lambda(v)
```

```{r}
dea.plot.frontier(input, output, RTS = 'vrs', xlab = 'input', ylab = 'output', main = 'Input vs Output using VRS')
```
```{r}
h <- dea(input, output, RTS = 'fdh+')
h
```
```{r}
peers(h)
lambda(h)
```
```{r}
dea.plot.frontier(input, output, RTS = 'fdh+', xlab = 'input', ylab = 'output', main = 'Input vs Output using FRH')
```


```{r}
fdh_v <- c(1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000)
crs_v <- c(1.0000, 1.0000, 1.0000, 1.0000, 0.9775, 0.8675)
drs_v <- c( 1.0000, 1.0000, 1.0000, 1.0000, 0.9775, 0.8675)
irs_v <- c(1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.8963)
vrs_v <- c(1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.8963)
frh_v <- c(1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000)
facility <- c('facility 1', 'facility 2', 'facility 3', 'facility 4', 'facility 5',  'facility 6')
```

```{r}
efficiency <- data.frame(facility, fdh_v, crs_v, drs_v, irs_v, vrs_v, frh_v)
efficiency
```


